102 make distinction between adding mutable and immutable properties to property list compile time based
globaltcad/sprouts pull request #103
Opened 2024-07-18 20:42 UTC by Gleethos

2024-07-23 20:35 UTC, Mazi-S requested changes
I really like the distinction between `val` and `var`. 

The only thing I noticed is that it is not entirely clear when it comes to adding a nullable `val`.

2024-07-23 20:35 UTC, Mazi-S commented on src/main/java/sprouts/Vars.java
> +    }
This is inconsistent with the other add `Val` methods.

Here we allow to add non-nullable `Vals` to a nullable `Vars` list.

2024-07-23 20:35 UTC, Mazi-S commented on src/test/groovy/sprouts/Properties_List_Spec.groovy
Perhaps we can also add similar tests that consider nullable lists.

2024-08-02 03:16 UTC, Gleethos commented on src/main/java/sprouts/Vars.java
> +    default Vars<T> add( Val<T> var ) {
Good point, I will fix that

2024-08-03 05:52 UTC, Gleethos commented on src/main/java/sprouts/Vars.java
> +    }
I agree! Pushed the changes. Thanks for noticing this!

2024-08-03 06:01 UTC, Gleethos commented on src/test/groovy/sprouts/Properties_List_Spec.groovy
I agree and added a few tests. Thanks for the suggestion.

2024-08-03 06:02 UTC, Gleethos commented
I pushed a whole lot of changes based on your feedback. Thank you!
Let me know if it is fine.

2024-08-07 07:36 UTC, Mazi-S commented on src/main/java/sprouts/Vars.java
> +    }
I totally agree. We should be consistent with the other add `Val` methods.
And I would also prefer the flexible approach you describe.

2024-08-07 07:45 UTC, Mazi-S reviewed
looks good :slightly_smiling_face:

2024-08-07 07:47 UTC, Mazi-S approved these changes

2024-08-08 14:56 UTC, merged